resilience4j.circuitbreaker:
  configs:
    default:
      waitDurationInOpenState: 5000
      failureRateThreshold: 50
      minimumNumberOfCalls: 5
  
  instances:
    addEpisode:
      baseConfig: default
